Traceback (most recent call last):
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
[As, Bs, Cs, Ds] = dm4bem.tc2ss(A, G, C, b, f, y)
Î¸s = ['Î¸1', 'Î¸3', 'Î¸6', 'Î¸7']       # state temperature nodes
uT = ['q0', 'q8', 'q10', 'q11']     # temperature sources
uQ = ['Î¸0', 'Î¸4', 'Î¸6', 'Î¸7']       # flow sources
u = uT + uQ                         # inputs
y = ['Î¸6']                          # output
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/vp/k617ngs97xq4vlzlj5ts6sch0000gn/T/ipykernel_6356/484680385.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;34m[[0m[0mAs[0m[0;34m,[0m [0mBs[0m[0;34m,[0m [0mCs[0m[0;34m,[0m [0mDs[0m[0;34m][0m [0;34m=[0m [0mdm4bem[0m[0;34m.[0m[0mtc2ss[0m[0;34m([0m[0mA[0m[0;34m,[0m [0mG[0m[0;34m,[0m [0mC[0m[0;34m,[0m [0mb[0m[0;34m,[0m [0mf[0m[0;34m,[0m [0my[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mÎ¸s[0m [0;34m=[0m [0;34m[[0m[0;34m'Î¸1'[0m[0;34m,[0m [0;34m'Î¸3'[0m[0;34m,[0m [0;34m'Î¸6'[0m[0;34m,[0m [0;34m'Î¸7'[0m[0;34m][0m       [0;31m# state temperature nodes[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0muT[0m [0;34m=[0m [0;34m[[0m[0;34m'q0'[0m[0;34m,[0m [0;34m'q8'[0m[0;34m,[0m [0;34m'q10'[0m[0;34m,[0m [0;34m'q11'[0m[0;34m][0m     [0;31m# temperature sources[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0muQ[0m [0;34m=[0m [0;34m[[0m[0;34m'Î¸0'[0m[0;34m,[0m [0;34m'Î¸4'[0m[0;34m,[0m [0;34m'Î¸6'[0m[0;34m,[0m [0;34m'Î¸7'[0m[0;34m][0m       [0;31m# flow sources[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mu[0m [0;34m=[0m [0muT[0m [0;34m+[0m [0muQ[0m                         [0;31m# inputs[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: tc2ss() takes 1 positional argument but 6 were given
TypeError: tc2ss() takes 1 positional argument but 6 were given

